---

spring:
  profiles: default
  
  
  
  security.jwt:
    tokenExpirationTime: 15 # Number of minutes
    refreshTokenExpTime: 60 # Minutes
    tokenIssuer: http://www.tss.com.pe
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus  
  
  
  mail:
    sender: campus@joedayz.pe
    fromIP: campus@joedayz.pe
    host: smtp.gmail.com
    username: campus@joedayz.pe
    password: password
    port: 465
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: false

  dataSource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/rrhh2
    username: root
    password: joedayz
    testOnBorrow: true
    removeAbandonedTimeout: 1800
    removeAbandoned: true
    validationQuery: select 1 from dual
    #validationQuery:  select sysdate from dual
    logAbandoned: true
    minEvictableIdleTimeMillis: 60000
    defaultReadOnly: false
    maxWait: 60000
    maxIdle: 1
    minIdle: 0
    maxActive: 50
    initialSize: 1
    test-on-connect: true



  jpa:
    #database-platform: org.hibernate.dialect.Oracle10gDialect
    #database-platform: org.hibernate.dialect.Oracle12cDialect
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    #generate-ddl= true.hibernate.ejb.interceptor=MyInterceptorClassName

    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy



    properties:
      hibernate:
          order_inserts: true
          order_updates: true
          ejb:
            interceptor: pe.com.tss.runakuna.jpa.RunaKunaEntityInterceptorImpl
          jdbc:
            batch_size: 400
            batch_versioned_data: true
            
multipart.maxFileSize: 20MB
multipart.maxRequestSize: 20MB            